services:
  app:
    build: .
    ports:
      - "3003:3003"
    volumes:
      - .:/app
    environment:
      - PORT=3003
    depends_on:
      - mysql-balance
  mysql-balance:
    image: mysql:5.7
    platform: linux/amd64
    container_name: mysql-balance
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: balances
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - ./.docker/mysql-balance:/var/lib/mysql