
# Creating Ze Galinha
# ID criado: c447793e-e985-47a8-b9f8-0da3042615ea
POST http://localhost:8000/clients HTTP/1.1
Content-Type: application/json

{
  "name": "Ze Galinha",
  "email": "ze@galinha.com"
}

###

# Creating Account para Ze Galinha
# ID criado: 01JCBJNZFP2G6QHBX9MJHDAGR3
POST http://localhost:8000/accounts HTTP/1.1'
Content-Type: application/json

{
  "client_id": "01JCBJNZFP2G6QHBX9MJHDAGR3"
}


###

# Creating Maria Galinha
# ID criado: 01JCBJPMXY1H52YGGG5FD328MT
POST http://localhost:8000/clients HTTP/1.1
Content-Type: application/json

{
  "name": "Maria Galinha",
  "email": "maria@galinha.com"
}

###

# Creating Account para Maria Galinha
# ID criado: c6b50a43-4faf-4a96-a1af-daa11b20ea9c
POST http://localhost:8000/accounts HTTP/1.1'
Content-Type: application/json

{
  "client_id": "01JCBJPMXY1H52YGGG5FD328MT"
}

###

# Creating a transaction from Maria Galinha to Ze Galinha
POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
  "from_account_id": "01JCBJMXSSV0EGRRJ69ND23NEV",
  "to_account_id": "01JCBJPGHCQA0DJRFAXWE32C68",
  "amount": 1
}

