CREATE TABLE clients (
    id VARCHAR(26) PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL
);


CREATE TABLE accounts (
    id VARCHAR(26) PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    client_id VARCHAR(26) NOT NULL,
    balance DECIMAL(10, 2) NOT NULL
);


CREATE TABLE transactions (
    id VARCHAR(26) PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    account_from_id VARCHAR(26) NOT NULL,
    account_to_id VARCHAR(26) NOT NULL,
    amount DECIMAL(10, 2) NOT NULL
);